name: Update Calendar

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout, build, and push
        run: |
          # Clone repo using built-in token
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git repo
          cd repo

          # Install dependency and run build script
          npm install ical
          node build-calendar.js

          # Commit and push if events.json changed
          git config user.name  "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add generated/events.json
          git diff --staged --quiet && echo "No changes." || (git commit -m "Auto-update calendar events [skip ci]" && git push)
